context:
  name: ddtrace
  version: 2.18.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ddtrace-${{ version }}.tar.gz
  sha256: 859d10ecf4cd2b9a58c2af38cf95d77bbaaca3c8f2527f0120f796d8afd57c53

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ddtrace-run = ddtrace.commands.ddtrace_run:main

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - make
  host:
    - python
    - setuptools-scm >=4
    - cython
    - cmake >=3.24.2,<3.28
    - setuptools-rust <2
    - setuptools
    - pip
  run:
    - python
    - envier >=0.5,<1.dev0
    - importlib-metadata <=6.5.0
    - opentelemetry-api >=1
    - protobuf >=3
    - typing_extensions
    - xmltodict >=0.12
    - wrapt >=1

tests:
  - python:
      imports:
        - ddtrace
  - requirements:
      run:
        - pip
    script:
      - pip check
      - ddtrace-run --help

about:
  summary: Datadog APM client library
  license: Apache-2.0 AND BSD-3-Clause AND 0BSD
  homepage: https://ddtrace.readthedocs.io/
  license_file:
    - LICENSE
    - LICENSE.BSD3
    - LICENSE.Apache
    - NOTICE

extra:
  recipe-maintainers:
    - aymondebroglie
    - SarvarD
    - zbowling
